.PHONY=install

WORKERS ?= 
BUILD_ONLY ?= 0
PROGRAMS_PATH ?= 
IS_PERSONAL ?= 

all: install

install:
	@NUM_WORKERS=$(WORKERS) \
		BUILD_ONLY=$(BUILD_ONLY) \
		PROGRAMS_PATH=$(PROGRAMS_PATH) \
		IS_PERSONAL=$(IS_PERSONAL) ./install.sh
