# Remote device tmux config (default)

###################################################################################################
############################################## SHELL ###############################################
###################################################################################################

# Set default shell to zsh
run-shell 'tmux set -g default-shell "$(command -v zsh)"'

# Allow passthrough: lets zsh bounce panel_title back through ssh back to user's tmux process :)
set -g allow-passthrough on

###################################################################################################

###################################################################################################
########################################## THEME & COLOR ##########################################
###################################################################################################

# Support true color
set -ga terminal-overrides ",xterm-256color*:Tc"

# My theme
source-file ${HOME}/.config/tmux/themes/monty.tmuxtheme

# set pane title for active panes
# my zsh agnoster customizations will print some of the more "static"
# prompt fields like hostname, username, cpu arch, gpu name (if detected)
# in there instead of polluting the terminal
set -g pane-border-status top
#set -g pane-border-format '#{?pane_active,#{pane_title},}'
set -g pane-border-format '#{pane_title}'

# other visual niceties 
set -g pane-border-indicators both              # arrows and colors indicating current pane

set -g pane-border-lines double                 # heavier border lines
# Choices: "single", "double", "heavy", "simple", "number", "spaces"

###################################################################################################

set -sg escape-time 10

# Focus events captured for better tui support
set -g focus-events on

###################################################################################################
######################################## PREFIX & SHORTCUTS #######################################
###################################################################################################
# Make <C-s> the binding
set -g prefix C-s
unbind C-b
bind C-s send-prefix

# Get rid of the damn right click menu
unbind -n MouseDown3Pane

# Disable annoying/duplicate shortcuts
unbind Space # layout cycle
unbind , # rename window
unbind $ # rename session
unbind , # show windows
unbind f # find window
unbind & # kill window
unbind % # vertical split
# horizontal split
unbind \"
unbind x # kill pane
unbind + # break into window
unbind - # restore into window

# Easier renaming/moving of windows and sessions
bind-key w command-prompt -I "#W" "rename-window '%%'"
bind-key r command-prompt -I "#S" "rename-session '%%'"
bind-key e command-prompt -I "#I" "move-window -t '%%'"

# New session
bind-key v new-session

# Some splitting that makes sense and isn't out of reach
bind | split-window -h
bind - split-window -v

# Vim key binds! 
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Vim movement to slightly adjust panes
bind H resize-pane -L 5
bind J resize-pane -D 5
bind K resize-pane -U 5
bind L resize-pane -R 5

# Give vim bindings in copy mode
setw -g mode-keys vi

# Because people try to scroll
set -g mouse on
