#!/bin/sh
# Monokai Pro - Based on:
# https://github.com/chriskempson/base16-shell/
# base16-shell (https://github.com/chriskempson/base16-shell)
# Base16 Shell template by Chris Kempson (http://chriskempson.com)
# Monokai scheme by Wimer Hazenberg (http://www.monokai.nl)
# Modified by Ali Hassani (@alihassanijr)

color00="00/06/0f" # Base 00 - Black
color01="fa/79/70" # Base 08 - Red
color02="7c/e3/8b" # Base 0B - Green
color03="fa/a3/56" # Base 0A - Yellow
color04="77/bd/fb" # Base 0D - Blue
color05="ce/a5/fb" # Base 0E - Magenta
color06="a2/d2/fb" # Base 0C - Cyan
color07="ec/f2/f8" # Base 05 - White
color08="89/92/9b" # Base 03 - Bright Black
color09=$color01 # Base 08 - Bright Red
color10=$color02 # Base 0B - Bright Green
color11=$color03 # Base 0A - Bright Yellow
color12=$color04 # Base 0D - Bright Blue
color13=$color05 # Base 0E - Bright Magenta
color14=$color06 # Base 0C - Bright Cyan
color15="ec/f2/f8" # Base 07 - Bright White
#color16="fd/97/1f" # Base 09
#color17="cc/66/33" # Base 0F
#color18="38/38/30" # Base 01
#color19="49/48/3e" # Base 02
#color20="a5/9f/85" # Base 04
#color21="f5/f4/f1" # Base 06

if [ -n "$TMUX" ]; then
  # Tell tmux to pass the escape sequences through
  # (Source: http://permalink.gmane.org/gmane.comp.terminal-emulators.tmux.user/1324)
  put_template() { printf '\033Ptmux;\033\033]4;%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_var() { printf '\033Ptmux;\033\033]%d;rgb:%s\033\033\\\033\\' $@; }
  put_template_custom() { printf '\033Ptmux;\033\033]%s%s\033\033\\\033\\' $@; }
elif [ "${TERM%%[-.]*}" = "screen" ]; then
  # GNU screen (screen, screen-256color, screen-256color-bce)
  put_template() { printf '\033P\033]4;%d;rgb:%s\007\033\\' $@; }
  put_template_var() { printf '\033P\033]%d;rgb:%s\007\033\\' $@; }
  put_template_custom() { printf '\033P\033]%s%s\007\033\\' $@; }
elif [ "${TERM%%-*}" = "linux" ]; then
  put_template() { [ $1 -lt 16 ] && printf "\e]P%x%s" $1 $(echo $2 | sed 's/\///g'); }
  put_template_var() { true; }
  put_template_custom() { true; }
else
  put_template() { printf '\033]4;%d;rgb:%s\033\\' $@; }
  put_template_var() { printf '\033]%d;rgb:%s\033\\' $@; }
  put_template_custom() { printf '\033]%s%s\033\\' $@; }
fi

# 16 color space
put_template 0  $color00
put_template 1  $color01
put_template 2  $color02
put_template 3  $color03
put_template 4  $color04
put_template 5  $color05
put_template 6  $color06
put_template 7  $color07
put_template 8  $color08
put_template 9  $color09
put_template 10 $color10
put_template 11 $color11
put_template 12 $color12
put_template 13 $color13
put_template 14 $color14
put_template 15 $color15

# Github dark colors
put_template 233 "0d/11/17"
put_template 235 "16/1b/22"
put_template 237 "21/26/2d"
put_template 243 "89/92/9b"
put_template 249 "c6/cd/d5"
put_template 252 "ec/f2/f8"
put_template 210 "fa/79/70"
put_template 178 "fa/a3/56"
put_template 114 "7c/e3/8b"
put_template 153 "a2/d2/fb"
put_template 75  "77/bd/fb"
put_template 27  "08/87/f7"
put_template 183 "ce/a5/fb"
put_template 54  "96/3c/f6"

color_foreground="ec/f2/f8"
color_background="0d/11/17"

# Custom
put_template 218 "fc/b1/ab"
put_template 186 "d7/d7/87"
put_template 228 "e2/d1/39"

## 256 color space
#put_template 16 $color16
#put_template 17 $color17
#put_template 18 $color18
#put_template 19 $color19
#put_template 20 $color20
#put_template 21 $color21

# foreground / background / cursor color
put_template_var 10 $color_foreground
if [ "$BASE16_SHELL_SET_BACKGROUND" != false ]; then
  put_template_var 11 $color_background
fi
put_template_custom 12 ";7" # cursor (reverse video)

# clean up
unset -f put_template
unset -f put_template_var
unset -f put_template_custom
unset color00
unset color01
unset color02
unset color03
unset color04
unset color05
unset color06
unset color07
unset color08
unset color09
unset color10
unset color11
unset color12
unset color13
unset color14
unset color15
unset color16
unset color17
unset color18
unset color19
unset color20
unset color21
unset color_foreground
unset color_background
