#!/usr/bin/env bash
# Document cat
# Uses PyMuPDF and Kitty's icat Kitten
# Tried pdftoppm, but to my surprise, it was slower.
# by Ali Hassani (@alihassanijr)

FILENAME=$1
THUMBNAIL="/tmp/pdfthumb.png"
shift

if [[ -w $THUMBNAIL ]]; then
	python3 -c "import fitz; doc = fitz.open('$FILENAME'); page = doc[0]; pix = page.get_pixmap(); pix.save('$THUMBNAIL');"
	kitty +kitten icat --silent --transfer-mode=stream "$@" $THUMBNAIL
	# Not removing because it causes weird flicks
	# My best guess is that it removes and icat fails to load
	#rm -r $THUMBNAIL > /dev/null
else
	echo "Failed to preview PDF file $FILENAME. /tmp is not writable."
fi
