#!/bin/bash
#
# Best solution I have so far to force VIFM
# to support true color without breaking my terminal
#
# Alias wouldn't work because zsh throws warnings when I
# try and change $TERM.

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Not supported on mac with alacritty
  vifm "$@"
else
  TERM="xterm-direct" vifm "$@"
fi
