#!/usr/bin/env bash
#
# Best solution I have so far to force VIFM
# to support true color without breaking my terminal
#
# Alias wouldn't work because zsh throws warnings when I
# try and change $TERM.

if ! command -v vifm >/dev/null 2>&1; then
  echo "vif: vifm not found." >&2
  exit 1
fi

if [[ "$OSTYPE" == "darwin"* ]]; then
  # Not supported on mac with alacritty
  vifm "$@"
else
  TERM="xterm-direct" vifm "$@"
fi
