#!/usr/bin/env bash
# Config list
# Author: Ali Hassani (@alihassanijr)
# NOTE: this should be sourced from ./dotfiles/


# Commonrc: things I want in both zsh and bash 
link_commonrc() {
  link_to_home "Commonrc" "commonrc" ".commonrc"

  link_to_home "Commonrc Extra" "commonrc-extra" ".commonrc-extra"
}

# Bashrc
link_bashrc() {
  link_to_home "Bashrc" "bashrc" ".bashrc2"
  # I don't overwrite ~/.bashrc, I think that's rude
  # I just have it source the extras I'd want, which 
  # is mostly just sourcing commonrc.
  SOURCEBASHRC="[ -f $HOME/.bashrc2 ] && source $HOME/.bashrc2"
  # Check if it's already appended
  if grep -Fxq "$SOURCEBASHRC" $HOMEDIR/.bashrc; then
      echo "Perfect! Looks like you already installed once. Skipping appending bashrc to ~/.bashrc because it's already there!"
  else
      echo "Appending bashrc to ~/.bashrc"
      echo $SOURCEBASHRC >> $HOMEDIR/.bashrc
  fi
}

# Inputrc
link_inputrc() {
  if [[ "$_OS_NAME" == "darwin" ]]; then
    link_to_home "Inputrc (mac)" "inputrc.mac" ".inputrc"
  else
    link_to_home "Inputrc" "inputrc" ".inputrc"
  fi
}

# Base16 colors
link_base16colors() {
  # Commonrc will read this if it exists
  link_to_home "Base16 Colors" "base16colors" ".base16colors"
}

# LS colors
link_lscolors() {
  # Commonrc will read this if it exists
  # Generated by vivid
  # https://github.com/sharkdp/vivid
  link_to_home "LS Colors" "lscolors" ".lscolors"
}

link_git_config() {
  link_to_home "Git config" "gitconfig" ".gitconfig"
}

link_fzf() {
  # apparently we need ~/.fzf for the vim plugins to work...
  local SRC_PATH=$FZF_DIR/.fzf
  local DST_PATH=$HOMEDIR/.fzf
  if [[ -d $SRC_PATH ]]; then
    echo "Linking .fzf: Symlink $SRC_PATH to $DST_PATH"
    [ -L "$DST_PATH" ] && rm $DST_PATH
    [[ -f "$DST_PATH" || -d "$DST_PATH" ]] && {
      echo "$DST_PATH exists and it is not a symlink. Resolve this before proceeding.";
      echo "ERROR: FZF symlink FAILED!";
      return 1
    }
    ln -s $SRC_PATH $DST_PATH
  fi
}

link_agentfiles() {
  if program_exists "claude"; then
    mkdir -p $HOME/.claude
    link_to_home "Claude config" "agentfiles/claude/settings.json" ".claude/settings.json"
    link_to_home "Claude prompt" "agentfiles/claude/CLAUDE.md" ".claude/CLAUDE.md"
    link_to_home "Claude memory index" "agentfiles/claude/MEMORY.md" ".claude/MEMORY.md"
    # Memory dir (link_to_home only handles files)
    local MEM_SRC="$THISDIR/agentfiles/claude/memory"
    local MEM_DST="$HOMEDIR/.claude/memory"
    if [[ -L $MEM_DST ]]; then
      local CURRENT_TARGET="$(readlink "$MEM_DST")"
      if [[ "$CURRENT_TARGET" == "$MEM_SRC" ]]; then
        echo "Claude memory dir already linked to $MEM_SRC; skipping."
      else
        echo "ERROR: ~/.claude/memory is a symlink to $CURRENT_TARGET, expected $MEM_SRC."
        echo "Remove or fix it manually, then re-run."
        exit 1
      fi
    elif [[ -d $MEM_DST ]]; then
      echo "ERROR: ~/.claude/memory exists as a real directory, not a symlink."
      echo "Move its contents into $MEM_SRC and remove ~/.claude/memory, then re-run."
      exit 1
    else
      echo "Linking Claude memory dir. Symlink agentfiles/claude/memory to ~/.claude/memory"
      ln -s "$MEM_SRC" "$MEM_DST"
    fi
    claude plugin marketplace add JuliusBrussee/caveman
    claude plugin install caveman@caveman
  fi

  if program_exists "codex"; then
    mkdir -p $HOME/.codex
    mkdir -p $HOME/.codex/rules
    link_to_home "Codex config" "agentfiles/codex/config.toml" ".codex/config.toml"
    link_to_home "Codex prompt" "agentfiles/codex/AGENTS.md" ".codex/AGENTS.md"
    link_to_home "Codex memory index" "agentfiles/codex/MEMORY.md" ".codex/MEMORY.md"
    link_to_home "Codex Claude-port rules" "agentfiles/codex/rules/claude-port.rules" ".codex/rules/claude-port.rules"
    # User-managed memory dir (link_to_home only handles files)
    local CODEX_MEM_SRC="$THISDIR/agentfiles/codex/memory"
    local CODEX_MEM_DST="$HOMEDIR/.codex/memory"
    if [[ -L $CODEX_MEM_DST ]]; then
      local CODEX_CURRENT_TARGET="$(readlink "$CODEX_MEM_DST")"
      if [[ "$CODEX_CURRENT_TARGET" == "$CODEX_MEM_SRC" ]]; then
        echo "Codex memory dir already linked to $CODEX_MEM_SRC; skipping."
      else
        echo "ERROR: ~/.codex/memory is a symlink to $CODEX_CURRENT_TARGET, expected $CODEX_MEM_SRC."
        echo "Remove or fix it manually, then re-run."
        exit 1
      fi
    elif [[ -d $CODEX_MEM_DST ]]; then
      echo "ERROR: ~/.codex/memory exists as a real directory, not a symlink."
      echo "Move its contents into $CODEX_MEM_SRC and remove ~/.codex/memory, then re-run."
      exit 1
    else
      echo "Linking Codex memory dir. Symlink agentfiles/codex/memory to ~/.codex/memory"
      ln -s "$CODEX_MEM_SRC" "$CODEX_MEM_DST"
    fi
    codex plugin marketplace add JuliusBrussee/caveman
  fi
}

# Custom scripts
link_custom_scripts() {
  # True color vifm
  link_bin "Vifm with truecolor (vif)" "scripts/vif" "vif"
  
  # Tmux split shortcuts
  link_bin "Tmux shortcuts (4w)" "scripts/4w" "4w"
  link_bin "Tmux shortcuts (4wc)" "scripts/4wc" "4wc"

  # SSH Agent Init
  if [[ "$_OS_NAME" == "darwin" ]]; then
    link_bin "SSH agent initializer (sagent)" "scripts/sagent.mac" "sagent"
  else
    link_bin "SSH agent initializer (sagent)" "scripts/sagent" "sagent"
  fi

  # SSH Agent killer
  link_bin "SSH agent killer (kssh)" "scripts/kssh" "kssh"

  if [[ -f "$HOME/.config/alacritty/alacritty.toml" ]]; then
    # Alacritty focus mode
    link_bin "Alacritty focus mode (alacritty_widescreen_toggle)" "scripts/alacritty_widescreen_toggle" "alacritty_widescreen_toggle"
  fi
}
