#!/usr/bin/env bash
# Config list
# Author: Ali Hassani (@alihassanijr)
# NOTE: this should be sourced from ./dotfiles/


# Commonrc-local: machine-specific settings, regenerated from the current
# OS/settings on every install. Sourced by commonrc *before* commonrc-extra
# so the user can still override anything here.
generate_commonrc_local() {
  # ssh-agent identity lifetime (see scripts/sagent). Personal devices get a
  # longer lifetime; shared/remote machines keep it short.
  local ssh_agent_ttl="2h"
  if [[ $IS_PERSONAL -eq 1 ]]; then
    ssh_agent_ttl="18h"
  fi

  echo "Generating Commonrc Local."
  cat > "$THISDIR/commonrc-local" <<EOF
# commonrc-local
# AUTO-GENERATED by the dotfiles installer (installer/configs.sh) from the
# detected settings. Do not edit by hand -- re-run the installer to regenerate.
# To override anything here, use ~/.commonrc-extra instead.

# ssh-agent identity lifetime (see scripts/sagent).
export SSH_AGENT_TTL="${ssh_agent_ttl}"
EOF
}

# Commonrc: things I want in both zsh and bash
link_commonrc() {
  link_to_home "Commonrc" "commonrc" ".commonrc"

  generate_commonrc_local
  link_to_home "Commonrc Local" "commonrc-local" ".commonrc-local"

  link_to_home "Commonrc Extra" "commonrc-extra" ".commonrc-extra"
}

# Bashrc
link_bashrc() {
  link_to_home "Bashrc" "bashrc" ".bashrc2"
  # I don't overwrite ~/.bashrc, I think that's rude
  # I just have it source the extras I'd want, which 
  # is mostly just sourcing commonrc.
  SOURCEBASHRC="[ -f $HOME/.bashrc2 ] && source $HOME/.bashrc2"
  # Check if it's already appended
  if grep -Fxq "$SOURCEBASHRC" $HOMEDIR/.bashrc; then
      echo "Perfect! Looks like you already installed once. Skipping appending bashrc to ~/.bashrc because it's already there!"
  else
      echo "Appending bashrc to ~/.bashrc"
      echo $SOURCEBASHRC >> $HOMEDIR/.bashrc
  fi
}

# Inputrc
link_inputrc() {
  if [[ "$_OS_NAME" == "darwin" ]]; then
    link_to_home "Inputrc (mac)" "inputrc.mac" ".inputrc"
  else
    link_to_home "Inputrc" "inputrc" ".inputrc"
  fi
}

# Base16 colors
link_base16colors() {
  # Commonrc will read this if it exists
  link_to_home "Base16 Colors" "base16colors" ".base16colors"
}

# LS colors
link_lscolors() {
  # Commonrc will read this if it exists
  # Generated by vivid
  # https://github.com/sharkdp/vivid
  link_to_home "LS Colors" "lscolors" ".lscolors"
}

link_git_config() {
  link_to_home "Git config" "gitconfig" ".gitconfig"
}

link_fzf() {
  # apparently we need ~/.fzf for the vim plugins to work...
  local SRC_PATH=$FZF_DIR/.fzf
  local DST_PATH=$HOMEDIR/.fzf
  if [[ -d $SRC_PATH ]]; then
    link_directory "$SRC_PATH" "$DST_PATH"
  fi
}

link_agentfiles() {
  if program_exists "claude"; then
    mkdir -p $HOME/.claude
    link_to_home "Claude config" "agentfiles/claude/settings.json" ".claude/settings.json"
    link_to_home "Claude prompt" "agentfiles/claude/CLAUDE.md" ".claude/CLAUDE.md"
    link_to_home "Claude memory index" "agentfiles/claude/MEMORY.md" ".claude/MEMORY.md"
    # Memory dir (link_to_home only handles files)
    link_directory "$THISDIR/agentfiles/claude/memory" "$HOMEDIR/.claude/memory"
    claude plugin marketplace add JuliusBrussee/caveman
    claude plugin install caveman@caveman
  fi

  if program_exists "codex"; then
    mkdir -p $HOME/.codex
    mkdir -p $HOME/.codex/rules
    link_to_home "Codex config" "agentfiles/codex/config.toml" ".codex/config.toml"
    link_to_home "Codex prompt" "agentfiles/codex/AGENTS.md" ".codex/AGENTS.md"
    link_to_home "Codex memory index" "agentfiles/codex/MEMORY.md" ".codex/MEMORY.md"
    link_to_home "Codex Claude-port rules" "agentfiles/codex/rules/claude-port.rules" ".codex/rules/claude-port.rules"
    # User-managed memory dir (link_to_home only handles files)
    link_directory "$THISDIR/agentfiles/codex/memory" "$HOMEDIR/.codex/memory"
    # don't let codex crash the installer because plugin is already installed!
    codex plugin marketplace add JuliusBrussee/caveman || {
      echo "codex caveman plugin install failed.";
      echo "this is probably nothing. codex tends to complain about this when it's already been installed.";
    }
  fi
}

# Custom scripts
link_custom_scripts() {
  # True color vifm
  link_bin "Vifm with truecolor (vif)" "scripts/vif" "vif"
  
  # Tmux split shortcut
  link_bin "Tmux shortcuts (4w)" "scripts/4w" "4w"

  # SSH Agent Init (unified mac/linux)
  link_bin "SSH agent initializer (sagent)" "scripts/sagent" "sagent"
}
